### ISSUE TITLE
'pip install py_entitymatching' error with command 'gcc' failed with exit status 1

### ISSUE THREAD

**Issue by habospace** [anhaidgroup/py_entitymatching#120]
Hi,

I encountered an error while installing the package, see details below:

Error message: 
Command “/opt/conda/bin/python -u -c “import setuptools, tokenize;__file__=‘/tmp/pip-install-jagug70a/py-stringsimjoin/setup.py’;f=getattr(tokenize, ‘open’, open)(__file__);code=f.read().replace(‘\r\n’, ‘\n’);f.close();exec(compile(code, __file__, ‘exec’))” install --record /tmp/pip-record-qmor4dym/install-record.txt --single-version-externally-managed --compile” failed with error code 1 in /tmp/pip-install-jagug70a/py-stringsimjoin/
error: command ‘gcc’ failed with exit status 1

mac OS Mojave: 10.14
Python version 3.7.2

**Comment by pjmartinkus** [comment]
Hi, thanks for bringing up this issue. We are currently working on a solution, but for the time being you can use one of two temporary solutions:

1. Use python 3.6: Right now, the package should be able to install on your OS if you use python 3.6 instead of 3.7.
2. Another solution could be to install from the source distribution. We've seen this issue before when installing with pip, but if you install from source and have the latest cython version, then it should work. For installation instructions take a look at [the documentation](http://anhaidgroup.github.io/py_entitymatching/v0.3.x/user_manual/installation.html#installing-from-source-distribution).

**Comment by habospace** [comment]
thanks, it works with python 3.6
